services:
  - type: web
    name: paas-comparison
    runtime: docker
    repo: https://github.com/alfranz/paas-comparison
    dockerfilePath: Dockerfile
    region: oregon 
    plan: free 
    branch: master 
    rootDir: .
    numInstances: 1
    healthCheckPath: /
    envVars:
    - key: PAAS
      value: RENDER
    - key: PORT
      value: 8082
  - type: cron
    name: date
    runtime: python
    schedule: "0 * * * *"
    buildCommand: "true" # ensure it's a string
    startCommand: date
    repo: https://github.com/render-examples/docker.git # optional