services:
  - type: web
    name: paas-comparison
    runtime: docker
    repo: https://github.com/alfranz/paas-comparison
    dockerfilePath: Dockerfile
    region: oregon 
    plan: free 
    branch: master 
    rootDir: .
    numInstances: 1
    healthCheckPath: /
    envVars:
    - key: PAAS
      value: RENDER
    - key: PORT
      value: 8082
